NEWS/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("summernote/", include("django_summernote.urls")),
    path("api/v1/", include("api.urls")),
    path("", include("newspaper.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

newspaper/models.py
from django.db import models


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # Don't create table in DB


class Category(TimeStampModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(TimeStampModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(TimeStampModel):
    STATUS_CHOICES = [
        ("active", "Active"),
        ("in_active", "Inactive"),
    ]
    title = models.CharField(max_length=200)
    content = models.TextField()
    featured_image = models.ImageField(upload_to="post_images/%Y/%m/%d", blank=False)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="active")
    views_count = models.PositiveBigIntegerField(default=0)
    published_at = models.DateTimeField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title


class Contact(TimeStampModel):
    message = models.TextField()
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(TimeStampModel):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    image = models.ImageField(upload_to="user_images/%Y/%m/%d", blank=False)
    address = models.CharField(max_length=200)
    biography = models.TextField()

    def __str__(self):
        return self.user.username


class Comment(TimeStampModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return f"{self.email} | {self.comment[:70]}"


class Newsletter(TimeStampModel):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email


## 1 - 1 Relationship
# 1 user can have 1 profile => 1
# 1 profile is associated to 1 user  => 1
# OneToOneField() => Can be used in Any Model


## 1 - M Relationship
# 1 user can post M post  => M
# 1 post is associated to only 1 user => 1
# In django use ForeignKey() => Must be used in Many side

# 1 category can have M posts => M
# 1 post is associated to only 1 category => 1


# 1 tag can have M posts => M
# 1 post can have M tags => M


## M - M Relationship
# 1 student can learn from M teachers => M
# 1 teacher can teach M students => M
# ManyToManyField() => Can be used in Any Model

# 1 post can contain M tag => M
# 1 tag can be used in M post => M

# 1 post can be associated to only 1 category => 1
# 1 category can contains M post => M

templates/aznews/list/right/categories.html
 
<aside class="single_sidebar_widget post_category_widget">
  <h4 class="widget_title">Category</h4>
  <ul class="list cat-list">
    {% for category in categories %}
      <li>
        <a href="{% url 'post-by-category' category.pk %}" class="d-flex">
          <p>{{ category.name|title }}</p>
          <p>({{ category.post_set.count }})</p>
        </a>
      </li>
    {% endfor %}
  </ul>
</aside>

templates/aznews/list/right/newsletter.html
<aside class="single_sidebar_widget newsletter_widget">
  <h4 class="widget_title">Newsletter</h4>
  <div id="newsletter_side_message"></div>
  <form action="" id="newsletter_side_form">
    {% csrf_token %}
    <div class="form-group">
      <input type="email"
             class="form-control"
             onfocus="this.placeholder = ''"
             onblur="this.placeholder = 'Enter email'"
             placeholder='Enter email'
             required
             name="email" />
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Subscribe</button>
  </form>
</aside>

templates/aznews/list/right/popular_posts.html
{% load static %}

<aside class="single_sidebar_widget popular_post_widget">
  <h3 class="widget_title">Recent Post</h3>
  {% for post in trending_posts %}
    <div class="media post_item">
      <img src="{{ post.featured_image.url }}"
           alt="{{ post.title }}"
           width="150px"
           height="80px" />
      <div class="media-body">
        <a href="{% url 'post-detail' post.pk %}">
          <h3>{{ post.title|truncatechars:25 }}</h3>
        </a>
        <p>{{ post.published_at|date:"F j, Y" }}</p>
      </div>
    </div>
  {% endfor %}
</aside>

templates/aznews/list/right/search_form.html
 
<aside class="single_sidebar_widget search_widget">
  <form action="{% url 'post-search' %}" method="get">
    <div class="form-group">
      <div class="input-group mb-3">
        <input type="text"
               class="form-control"
               placeholder='Search Keyword'
               onfocus="this.placeholder = ''"
               onblur="this.placeholder = 'Search Keyword'"
               name="query"
               value="{{query}}" />
        <div class="input-group-append">
          <button class="btns" type="button">
            <i class="ti-search"></i>
          </button>
        </div>
      </div>
    </div>
    <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
            type="submit">Search</button>
  </form>
</aside>

templates/aznews/list/right/tags.html
<aside class="single_sidebar_widget tag_cloud_widget">
  <h4 class="widget_title">Tag Clouds</h4>
  <ul class="list">
    {% for tag in tags %}
      <li>
        <a href="{% url 'post-by-tag' tag.pk %}">{{ tag.name }}</a>
      </li>
    {% endfor %}
  </ul>
</aside>